# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Bio-Das-Lite
version:      1.054
version_from: lib/Bio/Das/Lite.pm
installdirs:  site
requires:
    Carp:                          1.02
    English:                       1.01
    HTTP::Headers:                 1.64
    HTTP::Request:                 1.4
    LWP::Parallel::UserAgent:      0
    SOAP::Lite:                    0.69

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
